clouds:
  - bob
  - alice
  - watchtower

authdomains:
  - Default
  - cas

bob:
  authurl: http://openstack.cas.org:5000/v3
  region: RegionOne

alice:
  authurl: http://openstackprod.cas.org:5000/v3
  region: RegionOne  

watchtower:
  authurl: https://watchtower.openstack.cas.org:5000/v3
  region: RegionOne